### ISSUE TITLE
Something wrong in the code of val_loss function for  0-1 knapsack experiments

### ISSUE THREAD

**Issue by Felix-Feng** [Elizabethxyhu/NeurIPS_Two_Stage_Predict-Optimize#1]
Hi Eliza,

I took a close look at your code, and found there maybe something wrong in val_loss function of your 0-1 knapsack experiments.

https://github.com/Elizabethxyhu/NeurIPS_Two_Stage_Predict-Optimize/blob/main/code/0-1%20knapsack/train.py#L194

According to the code, "x" in Gurobi model seems to be equal to the first-stage decision, and "sigma" denotes the difference between the first- and second-stage decision. Then, the resulting objective of second-stage model is different to what you explained in Appendix C.2. Actually, it becomes $f^{\top} x_1^* - \sigma f^{\top} (x_1^* - x)$. Btw, the coefficient purchase_fee is also missed when formulating the compensation fee. 

Please feel free to share your feedback. Thanks.

**Comment by Elizabethxyhu** [comment]
Thank you for pointing out the mistakes in the val_loss function in the train.py in the 0-1 knapsack experiments.

Since "x" in Gurobi represents the first-stage decision and "sigma" represents the difference between the first and second stage decision, the objective function should be $purchase_fee * f^{\top} (x-\sigma) - compensation_fee * f^{\top} \sigma$.

In the code, the number of the compensation_fee already includes the coefficient purchase_fee, so purchase_fee is not appeared explicitly. Thank you for your question. we will write a comment to mentioned that.

I'll find the correct version of the file, updated the comments and upload it later. Thank you for pointing it out.

**Comment by Elizabethxyhu** [comment]
Thank you for posting this issue. After checking the code and appendix, I found that there might be some misunderstanding due to the variable naming of the code. According to the Appendix C.2., the objective function of the second-stage OP is: $\sum (purchasePersent * price_i)x_i - \sum (compensationPercent * purchasePersent * price_i)(x^*_{1i}-x_i)$, where $(purchasePersent * price_i)$ refers to $f_i$ and $(compensationPercent * purchasePersent * price_i)$ refers to $\sigma f_i$ in Equation (23) in Appendix C.2.

For simplicity, we use $\alpha$ to represent the purchase percent, and $\beta$ to represent the compensation percent. Then we have:
<img width="543" alt="Screenshot 2023-12-14 at 5 30 39 PM" src="https://github.com/Elizabethxyhu/NeurIPS_Two_Stage_Predict-Optimize/assets/59360139/35188e36-610f-4c1f-879e-39ec187cf1a8">

In the code, "x" represents the first-stage decision, i.e., <img width="16" alt="Screenshot 2023-12-14 at 5 46 20 PM" src="https://github.com/Elizabethxyhu/NeurIPS_Two_Stage_Predict-Optimize/assets/59360139/092e841e-5370-4619-ae78-2e123f498b4b">, and "sigma" represents the difference between the first and second-stage decision, i.e., <img width="40" alt="Screenshot 2023-12-14 at 5 47 04 PM" src="https://github.com/Elizabethxyhu/NeurIPS_Two_Stage_Predict-Optimize/assets/59360139/4f99d96b-b58a-478a-8afa-5a1b2f3a1936">
 Therefore, the code writes: 
<img width="357" alt="Screenshot 2023-12-14 at 5 36 15 PM" src="https://github.com/Elizabethxyhu/NeurIPS_Two_Stage_Predict-Optimize/assets/59360139/3464fad3-e497-4263-919b-2c2342a70ae0">
In the code, "purchase_fee" refers to $\alpha$, and "compensation_fee" refers to $(1+\beta)*\alpha$

We apologize for the misleading naming of variables in the code. Hope this comment can answer all your questions.

**Comment by Felix-Feng** [comment]
Thanks for your prompt feedback. 

However, I still have some questions regarding your objective in your code. Please see: https://github.com/Elizabethxyhu/NeurIPS_Two_Stage_Predict-Optimize/blob/main/code/0-1%20knapsack/train.py#L196
Here, I do not see the term $(1 + \beta)$ and the purchase percent $\alpha$ in your code when formulating $(1 + \beta) * \alpha * price_i * sigma_i$. 

Please take a check if I miss something. Thanks

**Comment by Felix-Feng** [comment]
Thanks for your prompt feedback.

However, I add a breakpoint at: https://github.com/Elizabethxyhu/NeurIPS_Two_Stage_Predict-Optimize/blob/main/code/0-1%20knapsack/train.py#L196
It looks that "compensation_fee" is NOT equal to $(1+\beta) * \alpha$ in the code. In fact, it takes the value of the compensation percent, which is initialized at https://github.com/Elizabethxyhu/NeurIPS_Two_Stage_Predict-Optimize/blob/main/code/0-1%20knapsack/train.py#L27

Please take a check if I miss something. Thanks

**Comment by Elizabethxyhu** [comment]
I think the reason for this misunderstanding is that the "purchase_fee" and "compensation_fee" are hardcoded. In lines 26 and 27, the code writes 
"purchase_fee = 0.2, compensation_fee = 0.21"
<=> $\alpha = 0.2, (1+\beta)*\alpha = 0.21$
<=> $\alpha = 0.2, \beta = 0.05$
For example, if a friend asks the buyer to buy a product for which the price is 100 dollars. The buyer will get 20 dollars as the profit if the buyer successfully buys the product. If the buyer promises to buy the product but cannot buy it back, the buyer cannot get the profit and will give the friend 1 dollar as compensation.

**Comment by Felix-Feng** [comment]
Well, it makes sense. Many thanks for your concrete explanation.
