### ISSUE TITLE
Train Size Issue of Alloy production

### ISSUE THREAD

**Issue by LucasBoTang** [Elizabethxyhu/NeurIPS_Two_Stage_Predict-Optimize#2]
Hello,

I noticed a potential issue in the file [`Alloy production/train.py`](https://github.com/Elizabethxyhu/NeurIPS_Two_Stage_Predict-Optimize/blob/main/code/Alloy%20production/train.py). Specifically, the variable `trainSize` is set to 350, which seems intended to limit the size of the training set.

However, after loading the data using `np.loadtxt` at [line 504](https://github.com/Elizabethxyhu/NeurIPS_Two_Stage_Predict-Optimize/blob/main/code/Alloy%20production/train.py#L504), the actual size of the dataset is `(7000, 4096)`, and there doesn't appear to be any code that truncates or selects the first 350 entries from the dataset. As a result, the full dataset is being used during training, which contradicts the intended behavior of limiting the training set to 350 samples.

Could you please clarify if this is the intended behavior or if the data should be truncated to match the `trainSize` parameter?

Thank you for your time and clarification!

Best regards,  
Bo

**Comment by LucasBoTang** [comment]
Hello,

I noticed that in the training data, the dimensions of the features (`x`), prices (`c`), and weights (`A`) are `(7000, 4096)`, `(7000,)`, and `(7000,)` respectively. However, the expected sizes for `c` and `A` should be `(700, 10)` and `(350, 2, 10)`.

What I’m particularly confused about is the mapping between the features (`x`) and the weights (`A`). Based on my understanding, the 7000 feature vectors of length 4096 correspond one-to-one with scalar values in `A`. 

Does this imply that the model's output is intended to be a single constraint coefficient derived from each feature vector?

Thank you for your time and help!

Best regards,  
Bo

**Comment by Elizabethxyhu** [comment]
Hello,

Thank you for posting this issue. After checking the code and appendix, I found that the code is correct and there might be some misunderstanding of the experiment setting. the variable “trainSize” refers to the size of the training instances, which is 350. The dataset of the features is (7000, 4096), containing all features for the 350 training instances.

As mentioned in Section 5 and Appendix C.1, for each instance of brass production, there are 2 kinds of metal materials and 10 suppliers. Since the unknown parameters are metal concentrations of each material from each supplier, there are 20 unknown parameters in each instance of brass production. Therefore, the prices (c ) and weights (G) are (10) and (2,10) for each instance of brass production. You can try to print this information by typing “print(c_torch.shape, G_torch.shape)” in line 335 in train.py. I think the reason for this misunderstanding is that we didn’t mention in Appendix C.1 that, in our experiments, the number of suppliers K is set to be 10. We apologize for such typos.

As for the relationship between the unknown parameters and features, as mentioned in Section 5, each unknown metal concentration, i.e., each constraint coefficient, is related to 4096 features. Therefore, the features for the training are (7000, 4096).

Hope this comment can answer all your questions.

Best,
Eliza

**Comment by LucasBoTang** [comment]
Hi Eliza,

Thank you so much for your detailed explanation. I now understand the experiment setting.
Once again, thank you for your swift and clear response!

Best regards,
Bo

**Comment by LucasBoTang** [comment]
Hello Eliza,

I have an additional question. I now understand that we have 350 training instances. However, I noticed that the prices, which have a length of 10, include 700 entries. Since these cannot be matched one-to-one with the training instances, I wanted to confirm my understanding.

Am I correct that you only used the first 350 prices in the experiments?

I am looking forward to hearing from you. Thank you so much.

Best regards,
Bo

**Comment by Elizabethxyhu** [comment]
Hi Bo,

Sorry for the late reply.
Yes. You are correct that we only used the first 3500 prices, i.e., 10 prices for each instance, in the experiments.

Best,
Eliza

**Comment by LucasBoTang** [comment]
Hi Eliza,

Thank you for your prompt feedback!

Bo
